// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, use_raw_strings, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmr8sXgBq1cXqIfXkEG3a4ZpxTBpUTgw0',
    appId: '1:855737924458:web:dbb6b70b8fe983ee868313',
    messagingSenderId: '855737924458',
    projectId: 'agenda-academica-13682',
    authDomain: 'agenda-academica-13682.firebaseapp.com',
    storageBucket: 'agenda-academica-13682.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0fAmv-tC7X5_wTHpHsSpu6nyeqVLNYdw',
    appId: '1:855737924458:android:385cf3ce5f585b81868313',
    messagingSenderId: '855737924458',
    projectId: 'agenda-academica-13682',
    storageBucket: 'agenda-academica-13682.firebasestorage.app',
    androidClientId:
        '855737924458-2857dsag5knr3tlv58m9fgma4f64gv1m.apps.googleusercontent.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmr8sXgBq1cXqIfXkEG3a4ZpxTBpUTgw0',
    appId: '1:855737924458:ios:iosplaceholder',
    messagingSenderId: '855737924458',
    projectId: 'agenda-academica-13682',
    storageBucket: 'agenda-academica-13682.firebasestorage.app',
    iosBundleId: 'com.example.agenda_academica_frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: 'YOUR_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    authDomain: 'YOUR_AUTH_DOMAIN',
    storageBucket: 'YOUR_STORAGE_BUCKET',
    iosBundleId: 'com.example.agendaAcademicaFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmr8sXgBq1cXqIfXkEG3a4ZpxTBpUTgw0',
    appId: '1:855737924458:web:windowsplaceholder',
    messagingSenderId: '855737924458',
    projectId: 'agenda-academica-13682',
    authDomain: 'agenda-academica-13682.firebaseapp.com',
    storageBucket: 'agenda-academica-13682.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDmr8sXgBq1cXqIfXkEG3a4ZpxTBpUTgw0',
    appId: '1:855737924458:web:linuxplaceholder',
    messagingSenderId: '855737924458',
    projectId: 'agenda-academica-13682',
    authDomain: 'agenda-academica-13682.firebaseapp.com',
    storageBucket: 'agenda-academica-13682.firebasestorage.app',
  );
}
